version: '3.1'

services:

  #db:
  #  image: mysql:5.7
  #  ports:
  #    - "3306:3306"
  #  volumes:
  #    - "C:\\mysql:/var/lib/mysql"
  #  environment:
  #    MYSQL_ROOT_PASSWORD: password123
  db2:
    image: mysql:8-debian
    ports:
      - "3306:3306"
    volumes:
      - "C:\\mysql8:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password123

  # micro:
  #   depends_on:
  #     - db
  #   build: ./
  #   image: demo:latest
  #   environment:
  #     - MYSQL_HOST=db
  #   ports:
  #     - "8080:8080"
