#spring.jpa.hibernate.ddl-auto=update
spring:
  cache: 
    cache-names: cache1
    caffeine:
      spec: maximumSize=500,expireAfterAccess=10s
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/example
    username: root
    password: password123
    driver-class-name: com.mysql.jdbc.Driver
#spring.jpa.show-sql: true

resilience4j.circuitbreaker:
  instances:
    dbback:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 10
      failureRateThreshold: 50
      automaticTransitionFromOpenToHalfOpenEnabled: true
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 20s


resilience4j.timelimiter:
  instances:
    dbback:
      timeoutDuration: 2s
      cancelRunningFuture: true

resilience4j.bulkhead:
  instances:
    dbback:
      maxConcurrentCalls: 2
      maxWaitDuration: 1s

resilience4j.thread-pool-bulkhead:
  instances:
    backendC:
      maxThreadPoolSize: 10
      coreThreadPoolSize: 10

management:
  health:
    db:
      enabled: true
      
  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: "health, metrics, loggers"
